### ISSUE TITLE
LSTM and FF baselines

### ISSUE THREAD

**Issue by ozancaglayan** [harvardnlp/hmm-lm#1]
Hello,

Could you share details on how did you obtain the LSTM and FFLM baselines? Thanks

**Comment by justinchiu** [comment]
Sure! I have the baselines available in a less clean repo ([FF](https://github.com/justinchiu/hmm-lm/blob/master/models/fflm.py), [LSTM](https://github.com/justinchiu/hmm-lm/blob/master/models/lstmlm.py)).
For the logs of the runs:
* [PTB FF](https://app.wandb.ai/justinchiu/hmm-lm/runs/153u818o)
* [PTB LSTM](https://app.wandb.ai/justinchiu/hmm-lm/runs/153u818o?workspace=user-justinchiu)
* [W2 FF](https://app.wandb.ai/justinchiu/hmm-lm/runs/3uivrqv5)
* [W2 LSTM](https://app.wandb.ai/justinchiu/hmm-lm/runs/1n02t3g0?workspace=user-justinchiu)

**Comment by ozancaglayan** [comment]
thank you!
